### ISSUE TITLE
Cuda indexing error during batch generation

### ISSUE THREAD

**Issue by nitaylevy** [stanfordnlp/pyreft#174]
I encountered an issue when trying to generate text with a trained reft model in batches. I chose layers 10-15 in Llama2-7b for interventions.

```
def generate_texts_batch(df, max_new_tokens=64, batch_size=10):
    all_continuation_texts = []
    all_generated_texts = []

    reviews = df["review"].tolist()

    with torch.no_grad():
        for i in tqdm(range(0, len(reviews), batch_size), desc="Generating"):
            batch_reviews = reviews[i:i+batch_size]

            # Tokenize batch with padding
            encoded = tokenizer(
                batch_reviews,
                return_tensors="pt",
                padding=True,
                truncation=True
            ).to(device)

            batch_size_actual = encoded["input_ids"].shape[0]
            
            # Last token per sequence in the batch
            base_unit_locations = (encoded["attention_mask"].sum(dim=1) - 1).tolist()
            intervention_locations = [
                [[loc] for loc in base_unit_locations] 
                for _ in range(len(config.layers))
            ]

            # Generate
            _, responses = reft_model.generate(
                encoded,
                unit_locations={"sources->base": (None, intervention_locations)},
                intervene_on_prompt=True,
                max_new_tokens=max_new_tokens,
                do_sample=True,
                eos_token_id=tokenizer.eos_token_id,
            )

```

Error

```
-- Debugging Info ---
Batch index: 0
Batch size (actual): 10
Input IDs shape: torch.Size([10, 32])
Attention mask shape: torch.Size([10, 32])
Base unit locations: tensor([31, 31, 31, 31, 31, 31, 31, 31, 31, 31], device='cuda:0')
Number of layers: 6
Sequence length per example: [32, 32, 32, 32, 32, 32, 32, 32, 32, 32]
--- End Debugging Info ---
--- Debugging Info ---
Batch index: 10
Batch size (actual): 10
Input IDs shape: torch.Size([10, 32])
Attention mask shape: torch.Size([10, 32])
Base unit locations: tensor([31, 31, 31, 31, 31, 31, 31, 31, 31, 31], device='cuda:0')
Number of layers: 6
Sequence length per example: [32, 32, 32, 32, 32, 32, 32, 32, 32, 32]
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1369: indexSelectSmallIndex: block: [5,0,0], thread: [32,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1369: indexSelectSmallIndex: block: [5,0,0], thread: [33,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1369: indexSelectSmallIndex: block: [5,0,0], thread: [34,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1369: indexSelectSmallIndex: block: [5,0,0], thread: [35,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_307/1224074907.py in <cell line: 0>()
----> 1 all_continuation_texts, all_generated_texts = generate_texts_batch(df_test, max_new_tokens=config.max_new_tokens)

/tmp/ipykernel_307/1585335691.py in generate_texts_batch(df, max_new_tokens, batch_size)
     96 
     97             # Generate
---> 98             _, responses = reft_model.generate(
     99                 encoded,
    100                 unit_locations={"sources->base": (None, intervention_locations)},

/usr/local/lib/python3.11/dist-packages/pyvene/models/intervenable_base.py in generate(self, base, sources, unit_locations, source_representations, intervene_on_prompt, subspaces, output_original_output, intervention_additional_kwargs, **kwargs)
   2156                         collected_activations += self.activations[key]
   2157         except Exception as e:
-> 2158             raise e
   2159         finally:
   2160             if set_handlers_to_remove is not None:

/usr/local/lib/python3.11/dist-packages/pyvene/models/intervenable_base.py in generate(self, base, sources, unit_locations, source_representations, intervene_on_prompt, subspaces, output_original_output, intervention_additional_kwargs, **kwargs)
   2143 
   2144             # run intervened generate
-> 2145             counterfactual_outputs = self.model.generate(
   2146                 **base, **kwargs
   2147             )

/usr/local/lib/python3.11/dist-packages/torch/utils/_contextlib.py in decorate_context(*args, **kwargs)
    114     def decorate_context(*args, **kwargs):
    115         with ctx_factory():
--> 116             return func(*args, **kwargs)
    117 
    118     return decorate_context

/usr/local/lib/python3.11/dist-packages/transformers/generation/utils.py in generate(self, inputs, generation_config, logits_processor, stopping_criteria, prefix_allowed_tokens_fn, synced_gpus, assistant_model, streamer, negative_prompt_ids, negative_prompt_attention_mask, use_model_defaults, custom_generate, **kwargs)
   2595 
   2596             # 12. run sample (it degenerates to greedy search when `generation_config.do_sample=False`)
-> 2597             result = self._sample(
   2598                 input_ids,
   2599                 logits_processor=prepared_logits_processor,

/usr/local/lib/python3.11/dist-packages/transformers/generation/utils.py in _sample(self, input_ids, logits_processor, stopping_criteria, generation_config, synced_gpus, streamer, **model_kwargs)
   3558                 is_prefill = False
   3559             else:
-> 3560                 outputs = model_forward(**model_inputs, return_dict=True)
   3561 
   3562             # synced_gpus: don't waste resources running the code we don't need; kwargs must be updated before skipping

/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py in _wrapped_call_impl(self, *args, **kwargs)
   1737             return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1738         else:
-> 1739             return self._call_impl(*args, **kwargs)
   1740 
   1741     # torchrec tests the code consistency with the following code

/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py in _call_impl(self, *args, **kwargs)
   1748                 or _global_backward_pre_hooks or _global_backward_hooks
   1749                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1750             return forward_call(*args, **kwargs)
   1751 
   1752         result = None

/usr/local/lib/python3.11/dist-packages/transformers/utils/generic.py in wrapper(self, *args, **kwargs)
    967 
    968         try:
--> 969             output = func(self, *args, **kwargs)
    970             if is_requested_to_return_tuple or (is_configured_to_return_tuple and is_top_level_module):
    971                 output = output.to_tuple()

/usr/local/lib/python3.11/dist-packages/transformers/models/llama/modeling_llama.py in forward(self, input_ids, attention_mask, position_ids, past_key_values, inputs_embeds, labels, use_cache, output_attentions, output_hidden_states, cache_position, logits_to_keep, **kwargs)
    686 
    687         # decoder outputs consists of (dec_features, layer_state, dec_hidden, dec_attn)
--> 688         outputs: BaseModelOutputWithPast = self.model(
    689             input_ids=input_ids,
    690             attention_mask=attention_mask,

/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py in _wrapped_call_impl(self, *args, **kwargs)
   1737             return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1738         else:
-> 1739             return self._call_impl(*args, **kwargs)
   1740 
   1741     # torchrec tests the code consistency with the following code

/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py in _call_impl(self, *args, **kwargs)
   1748                 or _global_backward_pre_hooks or _global_backward_hooks
   1749                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1750             return forward_call(*args, **kwargs)
   1751 
   1752         result = None

/usr/local/lib/python3.11/dist-packages/transformers/utils/generic.py in wrapper(self, *args, **kwargs)
    967 
    968         try:
--> 969             output = func(self, *args, **kwargs)
    970             if is_requested_to_return_tuple or (is_configured_to_return_tuple and is_top_level_module):
    971                 output = output.to_tuple()

/usr/local/lib/python3.11/dist-packages/transformers/models/llama/modeling_llama.py in forward(self, input_ids, attention_mask, position_ids, past_key_values, inputs_embeds, use_cache, output_attentions, output_hidden_states, cache_position, **flash_attn_kwargs)
    434             position_ids = cache_position.unsqueeze(0)
    435 
--> 436         causal_mask = self._update_causal_mask(
    437             attention_mask, inputs_embeds, cache_position, past_key_values, output_attentions
    438         )

/usr/local/lib/python3.11/dist-packages/transformers/models/llama/modeling_llama.py in _update_causal_mask(self, attention_mask, input_tensor, cache_position, past_key_values, output_attentions)
    506         # When output attentions is True, sdpa implementation's forward method calls the eager implementation's forward
    507         if self.config._attn_implementation == "sdpa" and not using_compilable_cache and not output_attentions:
--> 508             if AttentionMaskConverter._ignore_causal_mask_sdpa(
    509                 attention_mask,
    510                 inputs_embeds=input_tensor,

/usr/local/lib/python3.11/dist-packages/transformers/modeling_attn_mask_utils.py in _ignore_causal_mask_sdpa(attention_mask, inputs_embeds, past_key_values_length, sliding_window, is_training)
    286             if len(attention_mask.shape) == 4:
    287                 return False
--> 288             elif not is_tracing and torch.all(attention_mask == 1):
    289                 if query_length == 1 or key_value_length == query_length:
    290                     # For query_length == 1, causal attention and bi-directional attention are the same.

RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by willieseun** [comment]
Same here. It happens specifically with newer models like Qwen3

**Comment by willieseun** [comment]
I think I figured it out bro!
The issue comes from **when** the model is moved to GPU.  
If you call `get_peft_model()` or `get_reft_model()` *before* moving the base model to CUDA,  
the adapter layers can end up on CPU while the backbone is on GPU → leading to device mismatch errors.  

✅ Fix: move the base model to the device **immediately after initialization**, then wrap with PEFT/ReFT.  

Example:

```python
# 1. Load base model + tokenizer
model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    torch_dtype=torch.bfloat16,
    num_labels=n_classes,
    ignore_mismatched_sizes=True,
)
model.config.pad_token_id = tokenizer.pad_token_id
model.resize_token_embeddings(len(tokenizer))

# Important: move base model to GPU before wrapping
model.to(device)

# 2. Add PEFT (LoRA)
peft_config = LoraConfig(
    r=64,
    lora_alpha=256,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    layers_to_transform=[15],
    use_rslora=True,
    lora_dropout=0.05,
    bias="none",
    task_type=TaskType.SEQ_CLS,
)
model = get_peft_model(model, peft_config)

# 3. Add PyReft
reft_config = pyreft.ReftConfig(
    representations=[{
        "layer": l,
        "component": f"base_model.model.model.layers[{l}].output",
        "low_rank_dimension": 4,
        "intervention": pyreft.LoreftIntervention(
            embed_dim=model.config.hidden_size,
            low_rank_dimension=4
        )
    } for l in [15]]
)

model = pyreft.get_reft_model(model, reft_config)
model.model.enable_adapter_layers()

# 4. Debug: verify trainable params are on cuda
model.print_trainable_parameters()

**Comment by nitaylevy** [comment]
Yes, it worked for me too. Thank you! Saved me a lot of time.
